### ISSUE TITLE
v1.3.x: context.config.tags is not behave.tag_expression.TagExpression (v1)

### ISSUE THREAD

**Issue by ppisar** [behave/behave#1261]
In my test suite <https://github.com/rpm-software-management/ci-dnf-stack/blob/8f15099cd35da01df654a831e7bfcacccf0986b4/dnf-behave-tests/dnf/environment.py#L179> I check tags in `before_scenario()` hook using `context.config.tags.ands` iterator:

~~~~
def before_scenario(context, scenario):
    if "xfail" in scenario.effective_tags:
        skip = True
        for ors in context.config.tags.ands:
            if "xfail" in ors:
                skip = False
                break
        [...]
~~~~

But that stopped working after upgrading Behave from 1.2.6 to 1.3.1:

~~~~
# behave dnf
[...]
HOOK-ERROR in before_all: AttributeError: 'str' object has no attribute 'ands'
ABORTED: HOOK-ERROR in hook=before_all
~~~~

It looks like `context.config.tags` changed type from `behave.tag_expression.TagExpression` to `str`. Actually the object type depends in how behave is exectued. E.g. naming a tag results into `list` type:

~~~~
# behave --tags @dnf dnf
USING RUNNER: behave.runner:Runner
HOOK-ERROR in before_all: AttributeError: 'list' object has no attribute 'ands'
ABORTED: HOOK-ERROR in hook=before_all
~~~~

I was unable to find this change in Behave documentation.

Is it a bug in Behave, or do I use Behave incorrectly?

**Comment by ppisar** [comment]
Thanks for the pointers. I've already seen the documentation for Tag Expressions v2. But it only mentions changes in a command-line interface. But I have a problem with the Python API. Not with the command-line interface. (By the way, I tried switching the tag expression version and it had no effect on the API).

The API documentation for `behave.runner.Context.config` <https://behave.readthedocs.io/en/stable/api/#behave.runner.Context.config> reads:

> The attributes of this object are the same as the [configuration file section names](https://behave.readthedocs.io/en/stable/api/behave.html#configuration-files).

But the link return 404 error for me. Should it link to <https://behave.readthedocs.io/en/latest/behave/#configuration-files>? There is written:

>  tags : sequence<text>

That would correspond to the Python `list` type I saw. So why is it `str` if I don't pass any --tags command-line argument? How is the complex v2 expressions, e.g. the default `not (@xfail or @not_implemented)` one represented in the tags object? Maybe just as a unparsed, single string? That would match the `str` type I encountered.

**Comment by ppisar** [comment]
> * Why are not using the config-file instead of your more complex Python logic in the hooks ?
> 
Because we use the tags as a parameter for parameterizing the tests: We have tests which execute `dnf` program if Behave selects `@dnf` tag, the same test execute `dnf5daemon-client` program if Behave selects `@dnf5daemon` tag.

**Comment by jenisys** [comment]
Mmh, I am slightly confused.
`behave` does not select any tags, the `behave user` that uses `behave` does that either on command-line or in the the config-file.

As far as I understand it, you have chosen to use Python logic where the existing `behave` configuration functionality already provides you with a working and better solution.

OTHER POINT: Documentation related to Configuration-Files, etc.
* If you are using `behave v1.3.x`, you are using the latest **stable** version and not the **latest** version (which already has some changes that are not of interest for you).
* `Config.tags` is a list-of-strings that you provided on the command-line and/or config-file
* `Config.tag_expression` is the Tag-Expression object that you use to select elements/entities based on `Config.tags`.
* In the past, `Config.tags` was internally used for configuration from command-line/config-file and then internally replaced by the Tag-Expression object before you start w/ the test run.

SEE ALSO:
* https://behave.readthedocs.io/en/stable/behave/#configuration-files

**Comment by jenisys** [comment]
CLOSE IT: Questions were answered.
