### ISSUE TITLE
Run features (or scenarios) in parallel

### ISSUE THREAD

**Issue by julianpistorius** [behave/behave#235]
I have many features and scenarios - mostly using behaving (https://github.com/ggozad/behaving) to run browser tests, so they're fairly IO-bound. 

Currently behave runs these in a serial fashion and it's taking a very long time (16 minutes and growing). I have many processor cores lying idle. How feasible is it to run these scenarios in parallel?

I've thought of a few hacky ways to do it, but ideally this would be a feature of behave itself.

Some ideas from other testing frameworks:
- https://github.com/grosser/parallel_tests
- http://www.opencredo.com/2013/07/02/running-cucumber-jvm-tests-in-parallel/
- http://nose.readthedocs.org/en/latest/plugins/multiprocess.html
- https://pypi.python.org/pypi/Scribbler/0.3.1

**Comment by tomatobrown** [comment]
i would LOVE this!

**Comment by iElectric** [comment]
+1

**Comment by garlicPasta** [comment]
+1

**Comment by doup** [comment]
+1

**Comment by fedexcastro** [comment]
+1 any news about this?

**Comment by tomatobrown** [comment]
looks like it's scheduled for the 1.3 release...

**Comment by tomatobrown** [comment]
Is there any general idea of when the 1.3 release will be :)
:+1:

**Comment by jronald01** [comment]
+1 for any general idea when this might be :)

**Comment by phoebusliang** [comment]
+1

**Comment by vishalm** [comment]
+1000

**Comment by mubbashir** [comment]
+1

**Comment by carlosmmelo** [comment]
+1

**Comment by fedexcastro** [comment]
@jenisys, @julianpistorius, @tomatobrown guys, do you know if there is some advance on this feature?

**Comment by tomatobrown** [comment]
I think jenisys will be the one to do this one, I'm actually considering a move to cucumber/ruby because it's already coming in that framework

**Comment by julianpistorius** [comment]
@fedexcastro: No idea, sorry. We ended up rolling our own solution.

**Comment by vishalm** [comment]
Hi Guys Any update on this issue !! and when is the plan for the release !! Let me know if I can help

**Comment by vishalm** [comment]
Okey guys I figured out how to run behave tests parallel :) using behave-parallel. Let me know anyone want any help ... happy to help

**Comment by tomatobrown** [comment]
Yes please, I'll start a ticket in that repo

**Comment by SkyRG** [comment]
@vishalm which platform are you using? One of my team had some success on OSX but not on Windows | [issue](https://github.com/tokunbo/behave-parallel/issues/9)

**Comment by vishalm** [comment]
All 3 platform Ubuntu Linux Mac osx windows 7

**Comment by fedexcastro** [comment]
vishalm, is it working with the last version of behave? behave parallel seems to be forgotten since May 2014. https://github.com/tokunbo/behave-parallel

**Comment by vishalm** [comment]
Yes I made couple of required changes and it started working ... Now I am
doing parallel dockerized execution for better results

**Comment by fedexcastro** [comment]
@vishalm that's great, and do you have something else to join the results / reports?

**Comment by vishalm** [comment]
Right now using jenkins to run ... and getting awesome report in the end ..
as jenkin junit formatter do its magic and we dont need to worry about
different xml.

**Comment by TaniaMatvieieva** [comment]
@vishalm Do you have your own working fork for behave-parallel?

**Comment by vishalm** [comment]
No,

Just add this in your requirement file @TaniaMatvieieva

-e git+git://github.com/hugeinc/behave-parallel.git@a57eff3087aae9bd7519a7d4fc15228611db20b9#egg=behave-parallel


It will pull the most stable fork


and in all the steps file need to change the regex parser function:

use this ====> step_matcher("re")

instead of =====> use_step_matcher("re")

let me know if you still face any issues !!

**Comment by carlosmmelo** [comment]
@vishalm can you share the changes you did? I would like to try this.

**Comment by vishalm** [comment]
-e git+git://github.com/hugeinc/behave-parallel.git@a57eff3087aae9bd7519a7d4fc15228611db20b9#egg=behave-parallel


It will pull the most stable fork


and in all the steps file need to change the regex parser function:

use this ====> step_matcher("re")

instead of =====> use_step_matcher("re")

let me know if you still face any issues !!

**Comment by vishalm** [comment]
Ping me your email ID

**Comment by vishalm** [comment]
Here you go my friend.

Created a demo suite to run in parallel:
https://github.com/vishalm/behave_parallel_demo

**Comment by carlosmmelo** [comment]
Hmmm I see, thanks @vishalm it is a nice workaround; however I would love to see @jenisys solution no.1 above like he explained.

@jenisys is this still on the queue or been wip?

**Comment by hoadoanthingoc** [comment]
+1

**Comment by vishalm** [comment]
Glad to help you guys !!!

**Comment by mpseay** [comment]
+1

**Comment by quantoid** [comment]
+1

**Comment by carlosmmelo** [comment]
hopefully this would get added into `1.2.6` :smile:

**Comment by FelixQE1** [comment]
:+1:  +1

**Comment by jmoschino-personal** [comment]
+1

**Comment by inrix-yi-gu** [comment]
+1

**Comment by remcowesterhoud** [comment]
+1

**Comment by inrix-yi-gu** [comment]
+1

**Comment by gotlium** [comment]
+1

**Comment by remcowesterhoud** [comment]
This little runner can run features in parallel for you. https://gist.github.com/remcowesterhoud/f581b6b69587832da41507ab369f8b3c

Just add it in the main directory of the project and run it using:
```python behave-parallel.py```

I've edited so it works on Python3 and supports userdata. Just add the userdata like you normally would. With -p or --processes you can define the max number of processes.

**Comment by gerosalesc** [comment]
+1

**Comment by vishalm** [comment]
+1

**Comment by TageNielsen** [comment]
+1

**Comment by i4s-pserrano** [comment]
+1

**Comment by c-mart** [comment]
+1

**Comment by samgardner517** [comment]
+1

**Comment by dsounthi** [comment]
+1

**Comment by konstantinyakovskyiteamdev** [comment]
+1

**Comment by elchupanebrej** [comment]
+1

**Comment by carlosmmelo** [comment]
When working on this, please allow the ability to specify which tests scenario to run in serial (could be specified by tag like `serial_mode`) cause depending on the workflow (or complexity) against a single environment we might face data issue when trying to manipulate the same object.

**Comment by jenisys** [comment]
@carlosmmelo 
This already planned with the ``@sequential`` tag (applied to a feature).

**Comment by carlosmmelo** [comment]
great! thanks a lot for your hard work, we (at my company) really appreciate your efforts (and contributors too)!

**Comment by NothisIm** [comment]
@jenisys Is there any update on the feature development? Is it possible to speed up the process/contribute to the task?

**Comment by jenisys** [comment]
@NothisIm 
Sorry, I am currently rather busy. Therefore, it will still need some time before it is released. I probably provided as own repository (at least in the beginning), to allow it to evolve faster that behave. If you need something immediately, look at the other alternatives that are mentioned here.

And I need to update my milestones (I know) ;-)

**Comment by jenisys** [comment]
@NothisIm 
The intended design is described in [cucumber-jvm/issues/630](https://github.com/cucumber/cucumber-jvm/issues/630#issuecomment-215232021)

**Comment by borbamartin** [comment]
+1 (million) 😄

**Comment by President** [comment]
+1

**Comment by clymerrm** [comment]
+1

**Comment by ammarnajjar** [comment]
+1

**Comment by tomyan** [comment]
+1

**Comment by pokiz** [comment]
+1

**Comment by leoyu037** [comment]
+1

**Comment by evkostadinov** [comment]
+1

**Comment by carlosmmelo** [comment]
Hey @jenisys I was just wondering if you are planning to create a repo for this? I've been using the one provided by tokunbo but been having lot of issues specifically when I need to share a variable between the steps (context.foo for example) since tokunbo' context is shared between all the threads instead of a unique context on each thread. which is really messy when running multiple tests at the same time that does not hold the same values.

**Comment by jenisys** [comment]
An repo is planned. I will create/publish it after the next release of ``behave`` which should hopefully occur rather soon.

The own repo is intended to allow the parallel-runner to evolve faster that ``behave``. When a stable state is reached, the repo may become part of the ``behave`` repo.

**Comment by jgatkinsn** [comment]
This is so needed! Hope it can be finished soon :)

**Comment by fenwickipedia** [comment]
@jenisys will the behave-parallel repo be a complete behave install or will it be used with an existing installation? Any estimate on when the next behave release will be? Thank you!

**Comment by carlosmmelo** [comment]
🙏

**Comment by fnaval** [comment]
+1

**Comment by jenisys** [comment]
behave-parallel is intended as parallel runner for behave. It will use behave, but otherwise it just extends the funktionality by ist feature.

**Comment by jurgob** [comment]
+1

**Comment by Muschasgrazias** [comment]
+1

**Comment by GordonTester** [comment]
I'm a bit of a novice, but how would you extend this behave-parallel.py file to keep track of pass/fail counts and display them at the end?

**Comment by GordonTester** [comment]
How do you do it? :)

**Comment by frankvu191** [comment]
@vishalm I got this issue when running. Could you please help?
TypeError: string argument expected, got 'bytes'
I am running Python3.
Thanks,
Frank Vu

**Comment by vishalm** [comment]
@frankvu191 the project is on python 2.7

**Comment by nareshnayini** [comment]
I have used the command _$ python behave_parallel_scenario.py -t smoke --processes 2_
**But its executing all scenarios (66) instead of only smoke (9) scenarios. Can you please help.**

[INFO     2018-05-31 14:08:18,533] Found 10 features
[INFO     2018-05-31 14:08:18,533] Found 66 scenarios
[INFO     2018-05-31 14:08:18,533] Timeout for each scenario 300 seconds
[INFO     2018-05-31 14:08:18,534] Will execute 2 parallel process
[INFO     2018-05-31 14:08:18,534] --------------------------------------------------------------------------

**Comment by xrg** [comment]
@nareshnayini that "Found" message may be before they are filtered by tags. Please also consider the implementation at PR #616

**Comment by nareshnayini** [comment]
@xrg thanks for your reply.

**Comment by nareshnayini** [comment]
@vishalm I am also trying to follow the workaround provided by you.
Added this to requirements file:
-e git+git://github.com/hugeinc/behave-parallel.git@a57eff3#egg=behave-parallel 
I haven't used matcher in my code, so did not update anything on this.

When I execute the command `behave --processes 5 --parallel-element feature` got the below error:
File "features/environment.py", line 92, in before_all
    context.config.userdata['working_dir'] = get_working_dir()
AttributeError: 'Configuration' object has no attribute 'userdata'

Please help.

**Comment by vishalm** [comment]
Sure let me see

**Comment by Harishhr** [comment]
Hi,
i want to execute feature files in parallel so i tried to install behave-parallel available at this link https://pypi.org/project/behave-parallel/
but i am not able to install it and getting below error message:

Collecting behave-parallel
  Using cached https://files.pythonhosted.org/packages/05/9d/22f74dd77bc4fa85d391564a232c49b4e99cfdeac7bfdee8151ea4606632/behave-parallel-1.2.4a1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: 'c:\\users\\hah\\appdata\\local\\temp\\pip-build-ci4jol\\behave-parallel\\setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\hah\appdata\local\temp\pip-build-ci4jol\behave-parallel\

can someone please look into it and let me know what exactly i need to do.

**Comment by Harishhr** [comment]
My issue of installing behave-parallel is resolved. i did install it by taking this package form https://github.com/hugeinc/behave-parallel.

However after behave-parallel installation, if i execute feature files, command line argument are not getting recognized.
i am using behave 1.2.5

please help me.

**Comment by laripappa** [comment]
+1

**Comment by vishalm** [comment]
Let me look into that

**Comment by Sandmir** [comment]
I want to run behave-parallel with allure report, but got an error

usage: behave [options] [ [DIR|FILE|FILE:LINE] ]+
behave: error: format=allure_behave.formatter:AllureFormatter is unknown
        0.29 real         0.06 user         0.05 sys

can someone please look into it and let me know how I can fix it?

**Comment by anupmanekar** [comment]
> @vishalm I am also trying to follow the workaround provided by you.
> Added this to requirements file:
> -e git+git://github.com/hugeinc/behave-parallel.git@[a57eff3](https://github.com/behave/behave/commit/a57eff3087aae9bd7519a7d4fc15228611db20b9)#egg=behave-parallel
> I haven't used matcher in my code, so did not update anything on this.
> 
> _Using Python 3.6.4_
> 
> When I execute the command `behave --processes 5 --parallel-element feature` got the below error:
> File "features/environment.py", line 92, in before_all
> context.config.userdata['working_dir'] = get_working_dir()
> _**AttributeError: 'Configuration' object has no attribute 'userdata'**_
> 
> Please help.

@vishalm I am having this same issue? Do you have any insights? Using behave 1.2.5

**Comment by anupmanekar** [comment]
@vishalm @nareshnayini I found the issue. behave 1.2.5 has "userdata" support - https://github.com/behave/behave/blob/master/behave/configuration.py#L20

While the behave that is present in behave-parallel, doesnt have that support. And behave 1.2.5 doesnt have "processes" parameter support (https://github.com/hugeinc/behave-parallel/blob/upstreamsync/behave/configuration.py#L71) 

So in effect, will have to merge both versions for working with latest behave.

**Comment by vishalm** [comment]
It only work with python 2.7

**Comment by anupmanekar** [comment]
I am having python 2.7

**Comment by xrg** [comment]
Can you please try with my 'behave-parallel' of PR616 ? This is an alternate take on this implementation, may /behave/ differently wrt. such edge cases.

**Comment by neilhwatson** [comment]
I do not understand why behave did not have parallelism from day one, and that this thread is over 4 years old.

**Comment by tomatobrown** [comment]
yea, I moved to node js for this very reason 3 years ago

**Comment by jenisys** [comment]
@neilhwatson 
Interesting, normally only people are expected to complain if they contribute to a project. 
Therefore, I am expecting your pull-request with your own implementation of a parallel runner for behave rather soon.

**Comment by neilhwatson** [comment]
There already is one:  https://github.com/behave/behave/pull/616

**Comment by avinashkimidi** [comment]
> Okey guys I figured out how to run behave tests parallel :) using behave-parallel. Let me know anyone want any help ... happy to help

hey vishal i am new to behave ..could you plz tell me how to execute behave tests in parallel

**Comment by vishalm** [comment]
@avinashkimidi Added tavis.ci support for my project please see 
https://github.com/vishalm/behave_parallel_demo
Only constraint : Tested with 2.7 only
Again folks its a workaround not the real deal

**Comment by carlosmmelo** [comment]
:(

**Comment by QA-Rahul** [comment]
Can someone tell me how can I run a single or individual feature file using behave and allure? 

`behave -f allure_behave.formatter:AllureFormatter -o C:\\Users\\QA\\PycharmProjects\\webAutomationFramework\\allure-results `

Above command runs all the feature files but I need to run specific one.

**Comment by vishalm** [comment]
Reporting formatter is broken when u use behave parallel

**Comment by QA-Rahul** [comment]
@vishalm - Can you please then what is solution to store allure Html report into specific folder with behave?

**Comment by vishalm** [comment]
Why u want allure

It's just fancy cling

Automated test should be boolean 100% or 0% nothing in between.

**Comment by QA-Rahul** [comment]
I understand but how about reporting of tests without allure? The report is easy to understand for the non-technicals and other teams.

**Comment by vishalm** [comment]
Junit formatter that enough for jenkins.or any ci tool

**Comment by vishalm** [comment]
Educate them ...
